In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import OnehotTransactions

In [2]:
dataset = [['Broccoli', 'Green Peppers', 'Corn','Tomatoes','Beans'],
           ['Asparagus', 'Squash', 'Corn','Tomatoes'],
           ['Corn', 'Tomatoes', 'Beans', 'Green Peppers','Broccoli'],
           [ 'Corn', 'Tomatoes', 'Beans','Broccoli'],
           ['Broccoli','Green Peppers','Beans','Asparagus'],
          ['Green Peppers','Asparagus','Beans','Tomatoes'],
          ['Tomatoes','Corn','Beans','Asparagus','Green Peppers','Broccoli']]

In [31]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
print(df)

   Asparagus  Beans  Broccoli   Corn  Green Peppers  Squash  Tomatoes
0      False   True      True   True           True   False      True
1       True  False     False   True          False    True      True
2      False   True      True   True           True   False      True
3      False   True      True   True          False   False      True
4       True   True      True  False           True   False     False
5       True   True     False  False           True   False      True
6       True   True      True   True           True   False      True

In [25]:
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
print (frequent_itemsets)

     support                           itemsets
0   0.571429                        (Asparagus)
1   0.857143                            (Beans)
2   0.714286                         (Broccoli)
3   0.714286                             (Corn)
4   0.714286                    (Green Peppers)
5   0.857143                         (Tomatoes)
6   0.714286                  (Beans, Broccoli)
7   0.571429                      (Beans, Corn)
8   0.714286             (Beans, Green Peppers)
9   0.714286                  (Beans, Tomatoes)
10  0.571429                   (Corn, Broccoli)
11  0.571429          (Broccoli, Green Peppers)
12  0.571429               (Tomatoes, Broccoli)
13  0.714286                   (Tomatoes, Corn)
14  0.571429          (Tomatoes, Green Peppers)
15  0.571429            (Beans, Corn, Broccoli)
16  0.571429   (Beans, Broccoli, Green Peppers)
17  0.571429        (Beans, Broccoli, Tomatoes)
18  0.571429            (Beans, Corn, Tomatoes)
19  0.571429   (Beans, Green Peppers, Tomatoes)
20  0.571429         (Tomatoes, Corn, Broccoli)
21  0.571429  (Beans, Corn, Broccoli, Tomatoes)

In [26]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Beans),(Broccoli),0.857143,0.714286,0.714286,0.833333,1.166667,0.102041,1.714286
1,(Broccoli),(Beans),0.714286,0.857143,0.714286,1.000000,1.166667,0.102041,inf
2,(Corn),(Beans),0.714286,0.857143,0.571429,0.800000,0.933333,-0.040816,0.714286
3,(Beans),(Green Peppers),0.857143,0.714286,0.714286,0.833333,1.166667,0.102041,1.714286
4,(Green Peppers),(Beans),0.714286,0.857143,0.714286,1.000000,1.166667,0.102041,inf
5,(Beans),(Tomatoes),0.857143,0.857143,0.714286,0.833333,0.972222,-0.020408,0.857143
6,(Tomatoes),(Beans),0.857143,0.857143,0.714286,0.833333,0.972222,-0.020408,0.857143
7,(Corn),(Broccoli),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
8,(Broccoli),(Corn),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
9,(Broccoli),(Green Peppers),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
10,(Green Peppers),(Broccoli),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
11,(Broccoli),(Tomatoes),0.714286,0.857143,0.571429,0.800000,0.933333,-0.040816,0.714286
12,(Tomatoes),(Corn),0.857143,0.714286,0.714286,0.833333,1.166667,0.102041,1.714286
13,(Corn),(Tomatoes),0.714286,0.857143,0.714286,1.000000,1.166667,0.102041,inf
14,(Green Peppers),(Tomatoes),0.714286,0.857143,0.571429,0.800000,0.933333,-0.040816,0.714286
15,"(Beans, Corn)",(Broccoli),0.571429,0.714286,0.571429,1.000000,1.400000,0.163265,inf
16,"(Beans, Broccoli)",(Corn),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
17,"(Corn, Broccoli)",(Beans),0.571429,0.857143,0.571429,1.000000,1.166667,0.081633,inf
18,(Corn),"(Beans, Broccoli)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
19,(Broccoli),"(Beans, Corn)",0.714286,0.571429,0.571429,0.800000,1.400000,0.163265,2.142857
20,"(Beans, Broccoli)",(Green Peppers),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
21,"(Beans, Green Peppers)",(Broccoli),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
22,"(Broccoli, Green Peppers)",(Beans),0.571429,0.857143,0.571429,1.000000,1.166667,0.081633,inf
23,(Broccoli),"(Beans, Green Peppers)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
24,(Green Peppers),"(Beans, Broccoli)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
25,"(Beans, Broccoli)",(Tomatoes),0.714286,0.857143,0.571429,0.800000,0.933333,-0.040816,0.714286
26,"(Beans, Tomatoes)",(Broccoli),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
27,"(Tomatoes, Broccoli)",(Beans),0.571429,0.857143,0.571429,1.000000,1.166667,0.081633,inf
28,(Broccoli),"(Beans, Tomatoes)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
29,"(Beans, Corn)",(Tomatoes),0.571429,0.857143,0.571429,1.000000,1.166667,0.081633,inf
30,"(Beans, Tomatoes)",(Corn),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
31,"(Tomatoes, Corn)",(Beans),0.714286,0.857143,0.571429,0.800000,0.933333,-0.040816,0.714286
32,(Corn),"(Beans, Tomatoes)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
33,"(Beans, Green Peppers)",(Tomatoes),0.714286,0.857143,0.571429,0.800000,0.933333,-0.040816,0.714286
34,"(Beans, Tomatoes)",(Green Peppers),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
35,"(Tomatoes, Green Peppers)",(Beans),0.571429,0.857143,0.571429,1.000000,1.166667,0.081633,inf
36,(Green Peppers),"(Beans, Tomatoes)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
37,"(Tomatoes, Corn)",(Broccoli),0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
38,"(Tomatoes, Broccoli)",(Corn),0.571429,0.714286,0.571429,1.000000,1.400000,0.163265,inf
39,"(Corn, Broccoli)",(Tomatoes),0.571429,0.857143,0.571429,1.000000,1.166667,0.081633,inf
40,(Corn),"(Tomatoes, Broccoli)",0.714286,0.571429,0.571429,0.800000,1.400000,0.163265,2.142857
41,(Broccoli),"(Tomatoes, Corn)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
42,"(Beans, Corn, Broccoli)",(Tomatoes),0.571429,0.857143,0.571429,1.000000,1.166667,0.081633,inf
43,"(Beans, Corn, Tomatoes)",(Broccoli),0.571429,0.714286,0.571429,1.000000,1.400000,0.163265,inf
44,"(Beans, Broccoli, Tomatoes)",(Corn),0.571429,0.714286,0.571429,1.000000,1.400000,0.163265,inf
45,"(Tomatoes, Corn, Broccoli)",(Beans),0.571429,0.857143,0.571429,1.000000,1.166667,0.081633,inf
46,"(Beans, Corn)","(Tomatoes, Broccoli)",0.571429,0.571429,0.571429,1.000000,1.750000,0.244898,inf
47,"(Beans, Broccoli)","(Tomatoes, Corn)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
48,"(Beans, Tomatoes)","(Corn, Broccoli)",0.714286,0.571429,0.571429,0.800000,1.400000,0.163265,2.142857
49,"(Corn, Broccoli)","(Beans, Tomatoes)",0.571429,0.714286,0.571429,1.000000,1.400000,0.163265,inf
50,"(Tomatoes, Corn)","(Beans, Broccoli)",0.714286,0.714286,0.571429,0.800000,1.120000,0.061224,1.428571
51,"(Tomatoes, Broccoli)","(Beans, Corn)",0.571429,0.571429,0.571429,1.000000,1.750000,0.244898,inf
52,(Corn),"(Beans, Broccoli, Tomatoes)",0.714286,0.571429,0.571429,0.800000,1.400000,0.163265,2.142857
53,(Broccoli),"(Beans, Corn, Tomatoes)",0.714286,0.571429,0.571429,0.800000,1.400000,0.163265,2.142857

In [27]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)

In [28]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))

In [29]:
rules[ (rules['antecedent_len'] >= 2) &
       (rules['confidence'] > 0.75) &
       (rules['lift'] > 1.2) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,"(Beans, Corn)",(Broccoli),0.571429,0.714286,0.571429,1.0,1.40,0.163265,inf,2
2,"(Tomatoes, Broccoli)",(Corn),0.571429,0.714286,0.571429,1.0,1.40,0.163265,inf,2
4,"(Beans, Corn, Tomatoes)",(Broccoli),0.571429,0.714286,0.571429,1.0,1.40,0.163265,inf,3
5,"(Beans, Broccoli, Tomatoes)",(Corn),0.571429,0.714286,0.571429,1.0,1.40,0.163265,inf,3
6,"(Beans, Corn)","(Tomatoes, Broccoli)",0.571429,0.571429,0.571429,1.0,1.75,0.244898,inf,2
7,"(Beans, Tomatoes)","(Corn, Broccoli)",0.714286,0.571429,0.571429,0.8,1.40,0.163265,2.142857,2
8,"(Corn, Broccoli)","(Beans, Tomatoes)",0.571429,0.714286,0.571429,1.0,1.40,0.163265,inf,2
9,"(Tomatoes, Broccoli)","(Beans, Corn)",0.571429,0.571429,0.571429,1.0,1.75,0.244898,inf,2

In [30]:
rules[rules['antecedents'] == {'Beans', 'Corn'}]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,"(Beans, Corn)",(Broccoli),0.571429,0.714286,0.571429,1.0,1.40,0.163265,inf,2
6,"(Beans, Corn)","(Tomatoes, Broccoli)",0.571429,0.571429,0.571429,1.0,1.75,0.244898,inf,2

In [39]:
rules[rules['antecedents'] == {'Asparagus','Tomatoes'}]

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, antecedent_len]
Index: []